In [1]:
import numpy as np  

In [2]:
A = np.random.randint(1,10,(3,2))
B = np.random.randint(1,10,(3,2))

In [3]:
x = np.random.randint(1,10,3)

In [5]:
np.dot(x,x)

14

In [6]:
x

array([1, 2, 3])

In [7]:
np.outer(x,x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [9]:
A[1]

array([7, 7])

In [10]:
A

array([[8, 5],
       [7, 7],
       [6, 8]])